name: Build and publish image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . -t dheron/fplstatssr:latest
      - name: Push image to dockerhub
        run: |
          docker login -u dheron -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push dheron/fplstatssr:latest
